### ISSUE TITLE
Alignments vs alignment

### ISSUE THREAD

**Issue by sarjona** [concentricsky/badgr-server#121]
The OBv2.0 defines the field '**alignment**' inside the BadgeClass: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#BadgeClass
However, the Badgr.io only supports '**alignments**' (in plural): https://badgr.org/app-developers/api-guide/#badgeclass
Why are they different? The IMS validator (https://openbadgesvalidator.imsglobal.org/) only recognises the one defined in the specification ('alignment').

**Comment by ottonomy** [comment]
Great question, @sarjona. The v2 (and v1) Badgr API does not accept does not directly implement the OB data types, though it is closely aligned. In this case, a developer chose "alignments", and that's what it is for v2. It is likely that the next major version of our API will be even closer to the official data structure.

Badgr-server is certified as compliant by IMS, it's just not this API that delivers the compliant JSON. Those views are served by the /public/ API. Let us know if you have any more questions on this!

**Comment by sarjona** [comment]
For now, in Moodle, we're planning to leave the official 'aligment' element (as defined in OBv2.0), to make it compatible with the OBv2 specification.
When are you planning to release the next major version of your API? Will it support 'alignment' (instead of 'alignments'? Thanks a lot for your help and your quick answer!

**Comment by ottonomy** [comment]
@sarjona Great. Do not change your OBV2 implementation to "alignments", because that would make the alignment data disappear from the badges when they are processed (only "alignment" is valid in the https://w3id.org/openbadges/v2 context). 
Badgr is an OBV2 compliant issuer platform. In our public views (which serve the canonical URLs for BadgeClass objects) we use "alignment". Here's an example (there are no alignments in this badge, but you can see the property is spelled correctly for the spec as `alignment`. https://api.badgr.io/public/badges/kvZpfNM_TjilY3UvJCV4IQ.json The V2 Issuer API is not an OBV2 compliant API, nor will it be upgraded to become so, because this operation is not in scope for the Open Badges Specification. 

We don't have a scheduled release date for the `/v3/` version of the API, but there will be some changes this Q2 to support the forthcoming Badge Connect API, which does have standardized API endpoints in scope. Badgr-server will in those endpoints use `alignment` whenever BadgeClass data is relevant. Badge Connect may be the /v3/ version, or it may be separate. 

Hope that clarifies a little.

**Comment by sarjona** [comment]
Thanks a lot Nate! Yes, it does!! :-)
