### ISSUE TITLE
Can't import badge from badgr to mozilla backpack

### ISSUE THREAD

**Issue by 6tine** [concentricsky/badgr-server#133]
## System information & context:
- Operating system you are using: Ubuntu 12.04
- Browser & version: Chrome 74.0.3729.169

## Description of issue or feature request, including any error messages:
Hi !

I've created badges and issued them to an account which use my personal email address for testing. Now, I'm trying to import them to mozilla backpack, which is using my personal email address too, but I have this error : 

![image](https://user-images.githubusercontent.com/34345329/58239457-5eea2a80-7d49-11e9-8725-871097c39c63.png)

I've checked the badge assertion which is : 

`{"@context":"https://w3id.org/openbadges/v2","type":"Assertion","id":"http://192.168.38.212:8000/public/assertions/Ks_inGjZTdKEIImxQ6moIA","badge":"http://192.168.38.212:8000/public/badges/vJqPLnvSQmFXf_ZqHfj1A","image":"http://192.168.38.212:8000/public/assertions/Ks_inGjZTdKEIImxQ6moIA/image","verification":{"type":"HostedBadge"},"issuedOn":"2019-05-21T13:37:37+00:00","recipient":{"salt":"3319169b51334138aab00985f46c29e8","type":"email","hashed":true,"identity":"sha256$78ba8664e8e668cefec8107e5a3118749ee0c5739034d539a22139bd6a3e66ad"}}`

And when i'm trying to validate any badge with  https://badgecheck.io/ or https://ims-openbadges-validator.herokuapp.com/ it's not working. I have this error : 

![image](https://user-images.githubusercontent.com/34345329/58240745-e6389d80-7d4b-11e9-83b0-64b3b2f0a46e.png)

Do you have any idea what the problem could be ? Is it because the web sites are not public ? I can only access them in my local network (with port forwarding, which forward from my computer static IP to my virtual machine)

Thanks

**Comment by ottonomy** [comment]
Mozilla backpack only supports v1.1 badges, so if you import an image that has baked the "http://192.168.38.212:8000/public/assertions/Ks_inGjZTdKEIImxQ6moIA?v=1_1" url it should work (except for the fact that your local network IP address will not be reachable by the backpack verifier, but once your badgr-server is deployed on the publicly accessible internet it would work. You can get such an image from the /public/assertions/:entity_id/image?v=1_1 path.

In addition, within about a Month the Mozilla backpack will shut down and be replaced by information about how users can use Badgr, so don't worry too much about getting the backpack imports to work for now. We recently removed our compatibility feature in the UI that allows users to quickly be able to get to the legacy v1.1 version of the baked image because of the near term sunset of the Mozilla Backpack service.

**Comment by ottonomy** [comment]
The request timeout on the validator is almost certainly due to the network unreachability of your badgr-server from the validator server. We may do some work to reduce the internal timeouts to make it more likely to get a response back from the validator at the cost of requiring your server to respond more quickly.

**Comment by 6tine** [comment]
Ok thanks for the informations. I'll try when my server will be reachable from the outside. So badgr will replace Mozilla Backpack ?

**Comment by ottonomy** [comment]
Yes, see information about the transition of Backpack to Badgr here: https://support.badgr.com/portal/kb/articles/mozilla-backpack-transition-to-badgr-faqs
