### ISSUE TITLE
New problems with new instructions

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#22]
I noticed one very minor typo in readme.md: git clone https://github.com/concentricsky/badgr-server.git

Does not specify the 'code' directory, which is assumed in the next instruction.

However, the bigger issue (probably still small) is on pip install

pip install -r requirements-dev.txt
Downloading/unpacking python-resize-image==1.1.5 (from -r requirements.txt (line 18))
  Could not find a version that satisfies the requirement python-resize-image==1.1.5 (from -r requirements.txt (line 18)) (from versions: 1.1.3)
Cleaning up...
No distributions matching the version for python-resize-image==1.1.5 (from -r requirements.txt (line 18))

If I comment python-resize-image out of the requirements.txt, I get another error much later:

  Downloading mock-1.3.0.tar.gz (70kB): 70kB downloaded
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation

Perhaps you want to include instructions for setting up a development Python environment?
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

Unfortunately, those instructions install an older version of setuptools. My point is that the instructions still need some work. :)

**Comment by sacrophyte** [comment]
I was able to work around the problem with mock by running python ez_setup, as described here:
https://pypi.python.org/pypi/setuptools

**Comment by sacrophyte** [comment]
I got around the python-resize-image problem with a new package. I am not sure why a much earlier version was installed and why pip could not "see" the newer version.

https://pypi.python.org/pypi/python-resize-image/1.1.10

**Comment by sacrophyte** [comment]
Oh, I also changed the line in requirements.txt to accept a newer version (as opposed to just being stuck with python-resize-image 1.1.5):

python-resize-image~=1.1.5

**Comment by ottonomy** [comment]
This is two separate issues. To the first, thanks for indicating the missing directory instruction from our clone command in the instructions. This will be fixed with a future release.

To the second, there is a quirk in how that package is published to pypi. It can be fixed by upgrading pip or updating the package requirement to accept a newer version, as you have done. Leaving this issue open until we update the requirements in the next published commit. Most developer machines do not experience a problem, but we have experienced this issue on a couple "bare" installs of Linux (Ubuntu & CentOS) on server virtual machines.

**Comment by ottonomy** [comment]
Requirements have been updated to require `python-resize-image==1.1.10`. Thanks again!
