### ISSUE TITLE
grunt not found  :)

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#23]
I don't know anything about grunt - I thought I had it installed with ```npm install grunt```, but apparently, that was not enough:

(env)[cschultz@badgekit code]$ grunt dist
-bash: grunt: command not found

**Comment by sacrophyte** [comment]
I learned that both grunt and dist can be installed via npm. However, npm must first be updated to v2:

sudo npm -g install npm@latest

After that, I could install grunt and dist:
npm install grunt
npm install dist

I still do not understand the instructions in readme.md about ```grunt dist``` - what does that mean?


Is it just me, or do others get a whole both of characters outside the normal codebase?

**Comment by sacrophyte** [comment]
Perhaps the grunt-cli needs to be installed? This makes a little more sense:
http://gruntjs.com/getting-started
npm install -g grunt-cli

After doing that, I now get other errors:
```(env)[cschultz@badgekit code]$ grunt dist
Running "env:dist" (env) task

Running "sass:dist" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.

Aborted due to warnings.```

**Comment by sacrophyte** [comment]
More progress:

From: https://www.storelocatorplus.com/installing-sass-on-centos-6-5/

```sudo yum install rubygems```
```sudo gem install sass```

**Comment by ottonomy** [comment]
Thanks for the report. We will clarify the dependency instructions in the next release.

Grunt is required (though it will be installed as part of your usual `npm install`, and grunt-cli (both available on npm. Install grunt-cli globally) is strongly recommended, and required to use the `./manage.py dist` management command.

One thing incorrect in the above posts. `dist` is not a required npm package. Where `dist` appears in our documentation, it refers to our own custom commands, either the `dist` Django management command, available as `./manage.py dist` from within the root directory of this repository or also the `dist` task that command calls from grunt. In that case, `dist` is defined in Gruntfile.js and may occasionally be called directly as `grunt dist` if you have your grunt-cli installed or the local grunt npm module otherwise added to your $PATH.
