### ISSUE TITLE
Get All Issuers?

### ISSUE THREAD

**Issue by DanielJDufour** [concentricsky/badgr-server#282]
## System information & context:
- Operating system you are using: Ubuntu 18.04.4
- Browser & version: Chrome, Version 80.0.3987.149 (Official Build) (64-bit)
- URL or path of the screen where you encountered this issue or would like to see a new feature:
https://api.badgr.io/docs/v2

## Description of issue or feature request, including any error messages:
Hello.  I'm working on an implementation of badgr-server with a custom front-end.  We need a way to get a list of all of the issuers on the platform (in order to display a public page that lists all the issuers).  I was wondering if there was currently a way to do this with badgr-server.  Sending a GET request to /issuers seems to return only the issuers that are tied to my current user.  If there's not currently a way to do this, is this something that you would be interested in seeing?  I'm happy to build it out and contribute it.

If it doesn't make sense within the scope of badgr-server, I'm thinking that best approach would be to automatically tie a staff/machine account to all of the issuers on our implementation server and then create a Lambda function that proxies user requests for all the issuers to /issuers (and removes the PII on the return).

I'm sorry if I missed anything.  Happy to provide additional information.

Looking forward to your response and potentially contributing! :-)

**Comment by ottonomy** [comment]
@DanielJDufour it is not difficult to create such an endpoint. Things you'd want to think about:

* Definitely pagination. Understand which 
* use a `rw:serverAdmin` scope token to authenticate the request. 

You may consider using a variant of the IssuersChangedSince endpoint, which lets you paginate through the issuer set completely, and then in the future would allow you to get just a set of issuers that are new or changed since a particular timestamp. Almost all the code you need would be like this:

```
class AdminIssuersChangedSince(IssuersChangedSince):
    permission_classes = (IsServerAdmin,)

    def get_queryset(self, request, since=None):
        expr = Q(source_url=None)  # Our cached copies of remotely-defined issuers for imported badges may not needed for this endpoint

        if since is not None:
            expr &= Q(updated_at__gt=since)

        qs = Issuer.objects.filter(expr)
        return qs
```

**Comment by DanielJDufour** [comment]
Thank you!
