### ISSUE TITLE
Example of Auth Configuration

### ISSUE THREAD

**Issue by matty111** [concentricsky/badgr-server#351]
I installed badgr and I want to try to use my OAuth provider.

As Can I configure this /staff/oauth2_provider/application/add/ ?

what is the meaning of these fields?

![image](https://user-images.githubusercontent.com/58981392/102060150-1c3be780-3df2-11eb-9c5b-ff31a7285bd1.png)

**Comment by ottonomy** [comment]
These fields allow you to establish Badgr as an OAuth Provider so that relying parties can obtain API tokens to use the Badgr-server API. 

If you would like to allow users to sign into badgr with your IDP, you can set up an OAuth Provider, for example by implementing an OpenID provider https://django-allauth.readthedocs.io/en/latest/providers.html#openid activating that in your settings_local.py

Let me know if you have any questions.

**Comment by ram-pi** [comment]
@ottonomy adding in settings_local.dev.py something like:
`SOCIALACCOUNT_PROVIDERS = {
    'keycloak': {
        'KEYCLOAK_URL': "myrealurl",
    }
}`

I should be able to login via keycloak on the badgr-server? Is this configuration available also for the badgr-ui?
