### ISSUE TITLE
Prerequisite Issues

### ISSUE THREAD

**Issue by DongerZonie** [concentricsky/badgr-server#41]
In every OS I use, on the installation of the dependencies I can't find any of the devel packages

**Comment by sariabod** [comment]
@DongerZone The names listed in the instructions do not match. You have to do a bit of digging to find them. On the ubuntu variants I found many had just -dev as opposed to -devel. 

Here is a list (take this with a grain of salt because I still cannot get past the migrate state)

`apt-get install git
git-core 
python-virtualenv
gcc
python-pip 
python-dev 
libjpeg-turbo8 
libjpeg-turbo8-dev 
zlib1g-dev 
libmysqlclient-dev 
libsasl2-dev
swig 
libxslt-dev
automake 
autoconf 
libtool 
libffi-dev`

I didn't find anything for openldap. You may get an error running the "pip requirements" command. I installed openssl and openssllibs then manually install the latest version of cryptography.
`pip install cryptography`

**Comment by DongerZone** [comment]
I think I mightve found openldap
https://help.ubuntu.com/lts/serverguide/openldap-server.html

**Comment by ottonomy** [comment]
We've updated the package names. If there are any remaining issues for the couple platforms we provide examples for, feel free to reopen the ticket and describe which platform you are looking for dependencies for. We don't provide specific documentation for all platforms that Badgr may work on, but we may be able to help.
