### ISSUE TITLE
Question: any documentation for integration and API capabilities?

### ISSUE THREAD

**Issue by pjotrsavitski** [concentricsky/badgr-server#50]
Is there any documentation on conveniently pushing badges to Badgr service (similar to Backpack issuer API logic)? This would replace the manual one-by-one effort required to to import badges.

**Comment by ottonomy** [comment]
Great question. We are working with the DigitalMe team (that maintains the Mozilla Backpack) and Discendum (which maintains Open Badge Passport / Salava) to devise a common protocol for this type of push feature based around OAuth so that you only need to build one backpack integration to push badges to any compatible backpack.

**Comment by ottonomy** [comment]
We have now published https://badgr.org/app-developers/ which is a guide for developers looking to interact with Badgr's backpack capabilities on behalf of many users. 

Additionally, here's a presentation I gave last week about this issue on a more ecosystem-wide scale, talking about the forthcoming Badge Connect API that Badgr will adopt when it's available (when we finish writing it in the IMS workgroup) http://etherpad.openrecognition.org/p/ORA2018-September-12
