### ISSUE TITLE
Learning Pathways?

### ISSUE THREAD

**Issue by bryanlandia** [concentricsky/badgr-server#53]
Just a question:  are you going to open source Learning Pathways, and if so, do you have an idea when?  Thanks!

**Comment by ottonomy** [comment]
@bryanlandia great question. There will be an open standard "Open Pathways" that this will be based on, standardized within the same cluster as Open Badges, Extended Transcript, and CASE at IMS Global. We will be producing various systems that use Open Pathways in different ways, and I expect some of these will be open sourced. We're soon releasing a new version of Badgr server open source, but we will be moving the pathways component out of Badgr-server, because it makes more sense as a connected application. Very likely that we'll have authorship or viewing tools for pathways among our open source offerings.

**Comment by bryanlandia** [comment]
Thanks @ottonomy .  If someone is currently using Learning Pathways via Badgr.io will those be forward-compatible with the new connected application?

**Comment by ottonomy** [comment]
Yes. This feature is currently in a pre-release form within badgr-server on badgr.io but, the data in this app will be migrated to the new one, so our users can continue using pathways. Integrations agains the existing pathway sAPI (we don't know of any built outside our company yet) will likely need small updates to continue functioning.

**Comment by matty111** [comment]
In Master Branch is it possible use pathwat from badge-ui ? #253

**Comment by ywarnier** [comment]
@matty111 I see a pathway module in the app/ folder, but I haven't checked the details of how it works.

@ottonomy Is there any update (or where should I follow some updates from) on the inclusion of Open Pathways to IMS Global's open standards? I'd like to have a go at implementing Open Pathways in our LMS (chamilo) but I'm having a hard time understanding where to look for an open standard and whether this will look like the Comprehensive Learner Record (/Extended Transcript). Can you help me out a little? (just to place me on the right pathway, so to speak :smile: )
