### ISSUE TITLE
AssertionError at /v1/user/1

### ISSUE THREAD

**Issue by LewisOfTime** [concentricsky/badgr-server#56]
## System information: 
- Operating System
Windows 10 Pro 10.0.14393 Build 14393
- Browser & version:
Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)
- URL of the page where you encountered this issue:
http://localhost:8000/v1/user/1

## Description of issue, including any error messages:
I've set up a server in order to test, I have 1 user account set up and wanted to test the API but I can't use this endpoint as the AssertionError is thrown each time. 

Traceback: 
http://dpaste.com/1JZK43W

**Comment by ottonomy** [comment]
Hi, @LewisOfTime. 

This endpoint was errantly included in the urls.py in the build that is here on GitHub. We are planning a new Open Source release as soon as possible (sorry for delays, only less than 2 months left now) with massive updates to the features you now see on badgr.io and a few more forthcoming. This will include a whole new /v2 API that is more consistent. 

To test the API, try running the UI and seeing how it works, then select one of the calls it makes to try out on your own either on the /docs page or via an external client.

I will close this issue when the new code is posted and this issue is resolved.
