### ISSUE TITLE
badgr API : how to get the user entityId (or his assertions) from the email address?

### ISSUE THREAD

**Issue by pixeline** [concentricsky/badgr-server#58]
On our training center website, we would like to display our students along with the badges they have earned.

Via the API, I can get all the badges we've issued, I can get all the assertions, which give me the recipients as a hash. But I don't see how to get a given student's list of badges if I don't have his entity_id stored. 
What I'd like to be able to do : 

```php
$user = $badgr->getUserData('john.doe@foo.tld');
// User's badgr entity_id would be now in $user->entityId so that I can use it to get his badges.
```
In other words: is there a way to get all the assertions of a user by querying with his email address ?

Thank you,
a.
  
PS: just found that Mozilla's backpack solves this 
https://github.com/mozilla/openbadges-backpack/blob/master/docs/apis/displayer_api.md

**Comment by ottonomy** [comment]
Hi, @pixeline, thanks for the comment.

In order to access badges students have earned from other issuers (badges in their backpack/"My Badges" listing), you need to get their permission to share with you.

Badgr (in the almost-so-close-to-being-finalized) new open source update now incorporates the ability for connected applications to request permission to access these badges via OAuth2.

With a Bearer token in hand, you may request API endpoints as the recipient like /v2/backpack/assertions?include[]=badgeclass&include[]=issuer

The longer term plan for this approach is to also enable application registration endpoints, but we need to build the security model for that with the rest of our open source community. 

Looking forward to that release soon to be able to share this work publicly. (If people reading this are interested in early access, please contact me).

**Comment by pixeline** [comment]
Thank you. For the sake of mutual understanding :-) , let me clarify this :
> In order to access badges students have earned from other issuers (badges in their backpack/"My Badges" listing), you need to get their permission to share with you.

I actually only want the badges the student has earned with us, the BeCode issuer. Do they need to authorize that ?

**Comment by ottonomy** [comment]
@pixeline You may get that listing of badges with a `recipient` query parameter on one of the issuer API endpoints that you already have privileges to work with. This applies to both the issuer assertions list and the badgeclass-specific assertions list.

For example, `https://api.badgr.io/v2/issuers/{entity_id}/assertions?recipient=email@example.com`

**Comment by pixeline** [comment]
Hello @ottonomy,
I finally found some time to test this route and indeed it works very well. 
Yet, correct me if i'm wrong, but it does require that the user already had at least one assertion from the Issuer. This can cause problem because we will need to have them create their badgr account, then grant them a first badge before being able to use our custom application.
Would it be possible to simply do 

```https://api.badgr.io/v2/users/?recipient=email@example.com```

which would just return the entity_id, name, and assertions (if any) ?

Another way to solve this for us is to be able to POST an assertion by providing the badge id and user email (instead of user entity id).

**Comment by pixeline** [comment]
I wondered if perhaps your API did allow posting assertions using the email address but it appears it does not. POSTing this:

```json
{
  "entityType": "Assertion",
  "openBadgeId": "https://api.badgr.io/public/badges/m6fqvF-VQRifTsWEtQoBdQ",
  "badgeclassOpenBadgeId": "https://api.badgr.io/public/badges/m6fqvF-VQRifTsWEtQoBdQ",
  "issuer": "U1fM4KzWQZuXnpFXwG1gXw",
  "recipient": {
    "type": "email",
    "hashed": true,
    "plaintextIdentity": "alexandre@example.org"
  },
  "evidence": [],
  "revoked": false
}
````
returns : "identity" : "This field is required."
```json
{"status":{"description":"bad request","success":false},"validationErrors":[],"fieldErrors":{"recipient":{"identity":["This field is required."]}},"result":[]}
```

**Comment by pixeline** [comment]
I realize I'm actually diverting from this issue original request. Sorry about that. I will create a new issue.

**Comment by ottonomy** [comment]
@pixeline This thread is fine for now. I'll try to answer your questions.

> Yet, correct me if i'm wrong, but
> * it does not return the user entity id. (My plan was to store that in our db, to avoid further round trips to your servers)
> * it does require that the user already had at least one assertion from the Issuer. This causes us a problem because we will need to have them create their badgr account, then grant them a first badge manually on the Badgr website, before being able to use our own custom application.

You do not need a user entity_id to award a badge. Award the badge to the recipient identifier, typically an email address. 

When you get the error that the `identity` field is required, the error message is correct. Use `identity` instead of `plaintextIdentity`. The plaintext version is a read-only field. We will improve the documentation on the https://api.badgr.io/docs site as soon as possible to better describe which fields are required, but it will likely be another month.

Here are some comments on your suggested POST body:
```js
{
  "entityType": "Assertion", // read-only ignored
  "openBadgeId": "https://api.badgr.io/public/badges/m6fqvF-VQRifTsWEtQoBdQ", // read-only, ignored
  "badgeclassOpenBadgeId": "https://api.badgr.io/public/badges/m6fqvF-VQRifTsWEtQoBdQ", // ignored if "badge" entity id is in url path
  "issuer": "U1fM4KzWQZuXnpFXwG1gXw", // ignored
  "recipient": {
    "type": "email", // this is the default type
    "hashed": true, // this is the default value for typeemail
    "identity": "alexandre@example.org" // use this instead of plaintextIdentity
  },
  "evidence": [], // you may omit if evidence is none, but no harm to include the empty list like this.
  "revoked": false // ignored. To revoke a badge, send a DELETE request to the assertion detail endpoint.
}
```

A minimal POST body to /v2/badgeclasses/:entity_id/assertions or similar endpoint:
```js
{
  "recipient": {
    "identity": "alexandre@example.org"
  },
  "notify": true // set to true if you want Badgr to send an email.
}
```

Badgr does not require that recipients have Badgr accounts in order to be awarded badges, so you do not need to create accounts for your recipients before you can issue badges to them. You don't issue badges by user entity_id anyway, badges are always issued to a recipient identifier, like an email address.

> Would it be possible to simply do
> https://api.badgr.io/v2/users/?recipient=email@example.com
> which would just return the entity_id, name, and assertions (if any) ?

No, this is not public information. You need a user's permission to access their profile information and assertions they've earned (as I mentioned above, you may access assertions you have awarded using your issuer permissions, but you can't ask the user resource endpoints questions about users other than yourself or users you have OAuth tokens for). 

It is possible to get that information, you just need to ask users permission to get it first. We can set up a shared key/secret that allows you to ask users for OAuth tokens if you're ready. I thought this was what you were originally asking about when I said,

> Badgr (in the almost-so-close-to-being-finalized) new open source update now incorporates the ability for connected applications to request permission to access these badges via OAuth2.
> With a Bearer token in hand, you may request API endpoints as the recipient like /v2/backpack/assertions?expand=badgeclass&expand=issuer (corrected from original url)

Would you like more information about becoming a Badgr Connected App by implementing the OAuth side of Badgr? If so, let's get on the phone. Also, if on subsequent comments here you don't get a quick response from me, it's probably because I've lost it in my notifications -- feel free to send me an email directly or open a help ticket at help@badgr.io
