### ISSUE TITLE
Is there a way to change the salt or secret for the JWT token that is being generated

### ISSUE THREAD

**Issue by AshwinJd** [concentricsky/badgr-server#74]
How can we change the salt or the secret which is used to create the JWT token, as per our requirements?

**Comment by ottonomy** [comment]
@AshwinJd which JWT token are you referring to?

**Comment by AshwinJd** [comment]
The token that is being used for all the api calls. The access token which is stored in the admin portal.

**Comment by AshwinJd** [comment]
ok

**Comment by Yona-Appletree** [comment]
The deprecation is referring to the current method of authentication, yes. Not Badgr or Django.

The V2 API Docs are available through swagger on badgr.io, here: https://api.badgr.io/docs/v2/

@ottonomy can better answer about the configurability of the Random Token generator, but since it doesn't use a hashing function (as far as I know), salting it isn't really possible.
